services:
    frontend:
       image: jamallasomasekhar/techdome-frontend:v5
       ports:
         - 3000:3000
       env_file:
        - .env
       depends_on:
         - backend
       networks:
         - techdome-networks
    backend:
      image: jamallasomasekhar/techdome-backend
      ports:
        - 4000:4000
      env_file:
        - .env
      depends_on:
        - mongo
      networks:
        - techdome-networks
    mongo:
      image: mongo:latest
      ports:
        - 27017:27017
      # volumes:
      #    - mongo-data:/data/db
      networks:
        - techdome-networks
networks:
  techdome-networks: